# This workflow runs through the test suite

name: ci

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8

      - name: Install Dependencies
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Build Library
        run: bun run build

      - name: Build Docs
        run: bun --filter docs run build

      - name: Validate Docs Page Structure
        run: bun --filter docs run test:unit:ci

      - name: Run publint
        run: bun --filter bootstrap-vue-next run publint

      - name: Run publint on Nuxt package
        run: bun --filter @bootstrap-vue-next/nuxt run publint

      - run: bunx pkg-pr-new publish './packages/bootstrap-vue-next' './packages/nuxt' --template './templates/vite'

  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8

      - name: Install Dependencies
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Test Lint
        run: bun run test:lint:ci

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8

      - name: Install Dependencies
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Test Unit
        run: bun run test:unit:ci --filter=!docs
